server:
  port: 8082
dubbo:
  application:
    name: index-service
  registry:
    address: zookeeper://154.8.211.233:2181
  protocol:
    port: 20882
spring:
  redis:
    host: 154.8.211.233
    port: 6379
    jedis:
      pool:
        max-active: 20
    password: java1906
  datasource:
    url: jdbc:mysql://localhost:3306/qf-v6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
