server:
  port: 9083
dubbo:
  application:
    name: sso-consumer
  registry:
    address: zookeeper://154.8.211.233:2181
spring:
  redis:
    host: 154.8.211.233
    port: 6379
    password: 791187707
    jedis:
      pool:
        max-active: 10
  rabbitmq:
    host: 192.168.2.143
    port: 5672
    username: java1906
    password: 123456
    virtual-host: j1906
